### ISSUE TITLE
Export typings correctly in package.json

### ISSUE THREAD

**Issue by dd-jonas** [getsentry/sentry-javascript-bundler-plugins#183]
**Problem:**
I noticed when using the new `bundler` option under `moduleResolution` in TypeScript 5, that this package's type declarations are not compatible:

```
Could not find a declaration file for module '@sentry/vite-plugin'. '/node_modules/@sentry/vite-plugin/dist/esm/index.mjs' implicitly has an 'any' type.
There are types at '/node_modules/@sentry/vite-plugin/dist/types/index.d.ts', but this result could not be resolved when respecting package.json "exports". The '@sentry/vite-plugin' library may need to update its package.json or typings.
```

**Solution:**
Correctly set the types field in package.json, to make this package compatible with the new `moduleResolution` option.

**Comment by Lms24** [comment]
Hi @dd-jonas thanks for reporting!

Do you know if we have to provide the `exports` field in the `package.json` now or if there's another way (like the top level `types` attribute) to correctly resolve the types? The reason I'm asking is because we recently experimented with the `exports` field in the SDK packages and encountered some major problems while doing so. 

If you already have experience with this and would like to take a stab at fixing it, PRs are always welcome and we're happy to review. 

In the meantime, I'll backlog this as we're busy with other tasks.

**Comment by dd-jonas** [comment]
Hi @Lms24 

I don't have much experience with this unfortunately. As I can't tell the impact this will have like you mentioned, I'd rather not touch this myself.

**Comment by Xiot** [comment]
You just need to add
```json
"types": "./dist/types/index.d.ts"
```
to the default export.

```json
"exports": {
    ".": {
      "import": "./dist/esm/index.mjs",
      "require": "./dist/cjs/index.js",
      "types": "./dist/types/index.d.ts"
    }
  }
```
