### ISSUE TITLE
@sentry/webpack-plugin@2.0.0 installs its own copy of Webpack 4

### ISSUE THREAD

**Issue by wojtekmaj** [getsentry/sentry-javascript-bundler-plugins#255]
Installing the latest version of @sentry/webpack-plugin, 2.0.0, results in "webpack-4" dependency installed, along with ~250 other dependencies. This makes this plugin's install size [a whopping 51 MB](https://packagephobia.com/result?p=@sentry/webpack-plugin@2.0.0).

I understand there must be some reasoning behind this, and you probably spent much more time on this than I did, but this seems like a kind of workaround you should never be forced to do. I'm opening this thread in hope that we, as a community, could help out and figure something out to avoid this.

**Comment by lforst** [comment]
Hi, thanks for raising this :) I am gonna give some context so that we can come to a solution faster. I would also like to improve this.

So we obviously want to support both, webpack 4 and webpack 5. For a particular set of features (release value injection and debug Id injection) we currently use webpack's `BannerPlugin`. It was the easiest and most robust way of being able to inject values (at the top of the bundle!) while keeping source maps intact. Building our own plugin for this that was compatible with Webpack 4 and 5 AND kept source maps intact was a nightmare - I actually couldn't get it to work.

The thing is, webpack 4 and webpack 5 ship their `BannerPlugin`s differently. Webpack 5 makes it accessible through `compiler.webpack.BannerPlugin` inside plugins, essentially making us get away without any webpack dependency at all, whereas with Webpack 4 you have to directly import it.

I don't quite remember what I tried out already but here's some stuff I wanna try out making webpack a peer dependency and importing the plugin directly for v5 and v4.

**Comment by wojtekmaj** [comment]
Hmmm... Assuming `@sentry/webpack-plugin` can only be used with Webpack:

* `webpack: 4.x | 5.x` should be a peerDependency

And:

* For Webpack 5, we continue to use `compiler.webpack.BannerPlugin`, without the need of importing anything
* For Webpack 4, we could import`"webpack"` (which must be v4) provided to us by parent project

The problem is that:

```js
import { BannerPlugin as Webpack4BannerPlugin } from "webpack";
```

may crash when BannerPlugin is not exported, which I understand is the case with Webpack 5, hence the `… from "webpack-4"` trick.

But how about:

```js
import * as webpackMaybe4Exports from "webpack";
```

and then

```js
const BannerPlugin = compiler?.webpack?.BannerPlugin || webpackMaybe4Exports.BannerPlugin;

// …

new BannerPlugin(/* … */)
```
?

**Comment by dobladov** [comment]
I'm not familiar with the codebase my suggestion might not work, but could we have something like this to not have to import `webpack-4` when using `webpack-5`?

```diff
- import { BannerPlugin as Webpack4BannerPlugin } from "webpack-4";

function webpackReleaseInjectionPlugin(injectionCode: string): UnpluginOptions {
  return {
    name: "sentry-webpack-release-injection-plugin",
    webpack(compiler) {
      if (compiler?.webpack?.BannerPlugin) {
        compiler.options.plugins.push(
          new compiler.webpack.BannerPlugin({
            raw: true,
            include: /\.(js|ts|jsx|tsx|mjs|cjs)$/,
            banner: injectionCode,
          })
        );
      } else {
+        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
+        // @ts-ignore No typedefs for webpack 4
+        import("webpack-4").then(({BannerPlugin}) => {
          compiler.options.plugins.push(
            // eslint-disable-next-line @typescript-eslint/no-unsafe-argument, @typescript-eslint/no-unsafe-call
+            new BannerPlugin({
              raw: true,
              include: /\.(js|ts|jsx|tsx|mjs|cjs)$/,
              banner: injectionCode,
            })
          );
        })
      }
    },
  };
}
```
