### ISSUE TITLE
setCommits.ignoreMissing doesn't work anymore.

### ISSUE THREAD

**Issue by javimosch** [getsentry/sentry-javascript-bundler-plugins#283]
### Environment

self-hosted (I don't know the version)

Which SDK and version?
Latest Javascript

### Steps to Reproduce

Run webpack twice using setCommits.ignoreMissing to true

### Expected Result

The setCommits.ignoreMissing parameter works as expected.

### Actual Result

/cli/sentry-cli releases set-commits development --auto --ignore-missing
error: No commits found. Change commits range, initial depth or use --ignore-empty to allow empty patch sets.

Probably due to a CLI param rename?

**Comment by lforst** [comment]
@bmulholland I saw you downvoted the stalebot comment. Is this still an issue for you in the newest release of the webpack plugin?

**Comment by bmulholland** [comment]
@lforst well, it's fixed for me, and this was a year ago so I forget exactly what was going on, but the breaking change is still undocumented. There's [no mention of "ignore empty" in the docs](https://docs.sentry.io/product/)), and this Issue is actually one of the few relevant results on Google for "sentry ignore-empty". The only place so see anything about the option is in the source code itself, as I noted below, and a short note in the changelog that says it's a breaking change but not who it affects and what they should do about it.

Looking for this now, I also see a suggestion that using this option in the first place is a workaround for another problem, so I might try to fix that. The CLI message about the issue, or the docs would be a good place for Sentry to call that out, suggesting better ways to fix the issue (assuming it's indeed an anti-pattern of sorts).
 
Finally, as I noted above, my complaint was also about how a breaking change was rolled out without suitable communication. That wasn't addressed, which -- along with the continuing lack of docs -- is why I downvoted the bot.

**Comment by kamilogorek** [comment]
> There's [no mention of "ignore empty" in the docs](https://docs.sentry.io/product/)

That's due to making this option a default behavior as you already noticed. There's no reason for documenting it, as it's a no-op flag now.

> it's a breaking change but not who it affects and what they should do about it.

> Finally, as I noted above, my complaint was also about how a breaking change was rolled out without suitable communication. That wasn't addressed, which -- along with the continuing lack of docs -- is why I downvoted the bot.

It's a behavior change, but not really a breaking API change (though still marked as _breaking_ to make it easier to notice in the changelog). The flag is still there, hidden, but won't have any effect, to not force people to update their CIs scripts unnecessarily. This flag was used to allow creating initial commits patchset for "suspected commits" integration, or for branches that diverged in a way, that prevented the HEAD of CI job to find it's ancestor.
This should _not_ break the CI, but rather create a log warning, and this is exactly the current behavior.
We had lots of feedback from people saying that they'd expect it to work this way, so we initially rolled it out as an opt-in flag, but after a while, when moving to a new major version of the CLI, we made it a default.
