### ISSUE TITLE
[webpack & MFEs] Able to uniquely identified JS code associated with different teams

### ISSUE THREAD

**Issue by smeubank** [getsentry/sentry-javascript-bundler-plugins#323]
### Background
Micro frontends are inherently ambiguous outside of certain frameworks for MFE delivery (module federation for example). Ultimately users want to be able to keep their code and errors separated, to be able to understand where regressions might have occurred specifically and functionally to be able to route errors within their teams.

### Proposal
With our webpack plugin it is possible during build time to add identifiers to the generated/built code. For example the `debugId`s added in [Artifact Bundles](https://docs.sentry.io/platforms/javascript/sourcemaps/troubleshooting_js/artifact-bundles/).

Our webpack plugin similarly could inject unique id for code which should be respected as part of their own verticals. The SDK at runtime would then have access to these `containerId`s and could then be handled in beforeSend or similar, to route events generated to a specific DSN, add tags to be able to filter in the Sentry UI and more

- [ ]  can use injected IDs to populate events with information maintained by bundler-plugin to store on events as context to send to sentry
- [ ]  SDK will not make any automatic decision at this stage of routing (projects, teams, multiple projects or orgs etc)
- [ ]  ensure the data is populated in Sentry and consumable via API

**Consideration:**
This work will be restricted to only webpack plugin for now, but it is important to note that something like this could be applied outside of webpack, and inversely more specifically focus on Module Federation concepts. Then further if it might be useful one day to have this upstream in Module Federation, webpack generically and other bundlers.

For now I think it would be the best interest of ourselves and users to try and conform namings we choose to match those used withing webpack Module Federation to make it easy to understand for casual and expert users alike.

**Comment by zackarychapple** [comment]
@viktoriialurie, @valorkin, @scriptedalchemy, @brunos3d this is something to keep an eye on. There is quite a lot of value in getting this right.

**Comment by timfish** [comment]
I've put together a quick PoC using my [existing test repository](https://github.com/timfish/sentry-module-federation).

Before I submit a PR here, I decided to create a simple separate webpack plugin to demonstrate how this works in isolation.

In [every webpack configuration](https://github.com/timfish/sentry-module-federation/blob/main/app-05/webpack.config.js#L50-L52) you add the `SentryModuleDataPlugin`. You can pass any serialisable data to the constructor and this will be available later, and can be linked to the URL of the module: 
```ts
    new SentryModuleDataPlugin({
      team: "team-dialog",
    }),
```

The plugin [is quite simple](https://github.com/timfish/sentry-module-federation/blob/main/sentry-module-federation/src/plugin.ts) and works in much the same way as Sentrys debugId injection.

Then [in the host app](https://github.com/timfish/sentry-module-federation/blob/main/app-01/src/bootstrap.jsx#L9-L11) (or wherever you want to inspect an event to make routing/tagging decisions) you call `getFramesWithModuleData(event)` and it returns the error stack frames with each frame annotated with the data passed to `SentryModuleDataPlugin`, when available:

```ts
import { getFramesWithModuleData } from "sentry-module-federation";
import * as Sentry from "@sentry/react";

Sentry.init({
  dsn: "__DSN__",
  beforeSend: (event) => {
    console.log(getFramesWithModuleData(event));
    return event;
  },
});
```

So for example, with my demo repository:
- `yarn && yarn build && yarn start`
- Open `localhost:3001`
- Click `Dialog` > `Open Dialog` > `Nice`
![image](https://github.com/getsentry/sentry-javascript-bundler-plugins/assets/1150298/6f9e6233-81e5-45a2-a60c-b268b24dea12)
- An uncaught error is thrown
- Check the console to see the frames with additional module annotations under `moduleData`. Note the last frame is where the error was thrown:
![image](https://github.com/getsentry/sentry-javascript-bundler-plugins/assets/1150298/d45ed7fe-e88f-4cb3-9e1a-dc2f5e9c3619)
 
This data can then be used to route or tag events appropriately. Some users may only want to consider the annotation data at the frame where the error occurred and others might be interested in routing or tagging based on more frames or every frame in the stack trace.

**Comment by zackarychapple** [comment]
Am I correct in assuming that this means that the tracing through multiple layers of hosts / remotes will work as well?

**Comment by cfryerdev** [comment]
I really like this concept, happy to give it a go on one of my projects with many teams owning multiple remotes. What are your thoughts on potentially allowing a reference to a codeowners file as an optional parameter?

**Comment by AbhiPrasad** [comment]
> Am I correct in assuming that this means that the tracing through multiple layers of hosts / remotes will work as well?

As long as a stacktrace exists we should be able to trace back through multiple layers.

The issue here is when the stacktrace is eliminated like when you use `Promise.then()`- but we can encourage async/await to avoid this. This is only a 95% perfect soln though, because with things like event listeners and third party scripts we'll always end up with gaps. This gets solved with the [tc39 async context proposal](https://github.com/tc39/proposal-async-context) though, so I think we can just establish this baseline and then wait for that to resolve all our use cases.

> What are your thoughts on potentially allowing a reference to a codeowners file as an optional parameter

We could theoretically tag any frame with this additional metadata, it might make sense we expose an annotation API from the plugin itself.

**Comment by realkosty** [comment]
@timfish Very exciting to see this happen 🙂

> Some users may only want to consider the annotation data at the frame where the error occurred and others might be interested in routing or tagging based on more frames or every frame in the stack trace.

Love the flexibility!!

Curious, what are the benefits of this design?

`moduleData: {team: 'team-dialog'}`

vs something simpler like

`moduleName: 'dialog'`

the later has following benefits: 
1. Having a single fixed key-value would allow adding a drop down in Sentry UI (e.g. Issue stream filter like environment). It might be possible with the original approach but there will be ambiguity (multiple keys) and some UX questions (displaying tag name vs. fixed "Module" UI label, naming confusion with Sentry's #-teams)
2. simpler, easier to code
3. user-defined `team` key seems redundant as Sentry's #-teams can be mapped using Issue Owners based on `moduleName` tag.

@smeubank what do you think?

**Comment by realkosty** [comment]
> This is only a 95% perfect soln though, because with things like event listeners 

Hey @AbhiPrasad, so assuming we have a complete stacktrace of the exception thrown from an event handler wouldn't we be able to reliably map it to `moduleData` based the info injected into the file in which event handler's code lives in?

**Comment by timfish** [comment]
> Curious, what are the benefits of this design?
> `moduleData: {team: 'team-dialog'}`

You can pass any serialisable data through from the webpack plugin to runtime. You could just pass a string if that's all you require but the reason I went for a serialised object was so you can pass more complex data through. 

For example, from the remote apps, you may want to pass both the DSN and the release so these can be used to route to different Sentry projects at runtime.

```ts
new SentryModuleDataPlugin({
  team: 'team-dialog',
  release: "dialog@1.2.3",
  dsn: '__PUBLIC_DSN__'
}),
```

**Comment by AbhiPrasad** [comment]
> Hey @AbhiPrasad, so assuming we have a complete stacktrace of the exception thrown from an event handler wouldn't we be able to reliably map it to moduleData based the info injected into the file in which event handler's code lives in?

yup if we have the complete stacktrace all will be good - only issues will arise if the stacktrace is not available/not complete because of async callbacks used by event listeners/async built-ins like `setTimeouts`

**Comment by realkosty** [comment]
> For example, from the remote apps, you may want to pass both the DSN and the release so these can be used to route to different Sentry projects at runtime.

@timfish thanks for explaining, I get it now!

Then here's my feedback:

1. We should ship this together with:
* `ModuleDataIntegration` that picks up module data from topmost stack frame and automatically sets tags from that data (including overriding host application's `release`)
* `ModuleDataMultiplexedTransport` that picks up module data from topmost stack frame and send it to `dsn`

This would relieve most customers from having to write lots of boilerplate. But leave the option to walk the stacktrace manually for those few customers that have special use case.

2. `team` is just an arbitrary key used as an example, right? Then maybe we should use something like `component` instead (to avoid conflict with `module` and not be tied to just Webpack with `webpackModule`). This could be used by folks who don't want separate projects but still want a tag to filter issue stream, set up alerts, code ownership etc. I.e. they would choose to use `ModuleDataIntegration` but not `ModuleDataMultiplexedTransport`. If we establish a good key convention like `component` we can later add it in the UI as a dropdown box similar to Environment.

I am against `team` because I've seen many customers with lots of micro-frontends (like 50, 100+) and just a few teams. They would loose that information by using `team` tag. While they can always map `tag:component` to the right team in Ownership rules. Plus there would be no way to enforce that values of `team` actually match teams defined in Sentry, and it would mismatch GitHub teams in CODEOWNERS file.

Does that make sense?

**Comment by lforst** [comment]
@realkosty Thank you for the insight!

Based on the feedback in this thread, injecting module metadata seems like an approach that would work.

---

Let's come up with a plan of action:

#### 1. Plugins

We add a (for now experimental) new option to the Plugins that will be able to inject arbitrary data into bundles that is referencable via filename/stacktrace (similar to debug IDs).

Since we assume users want to inject arbitrary data we provide a way to do so, in addition to some canonical fields.

Suggestion:

```ts
sentryBundlerPlugin({
  org: 'myorg',
  project: 'myproj'
  release: {
    dist: 'foo'
  },
  _experiments: {
    moduleMetadata: (calbackOptions: {
      entrypoint?: string; // we might want to inject for only certain entrypoints
      release?: string; // callback param because release name could be dynamically picked up by the plugin
    }) => ({
      this: 'is',
      arbitrary: 'serializable',
      data: '!',
      entrypoint: callbackOptions.entrypoint
      release: callbackOptions.release
    })
    // instead of a callback, moduleMetadata can also be any serializable value
  }
})
```

is supposed to inject the following data into each bundle:

```json
{
  "dist": "foo",
  "this": "is",
  "arbitrary": "serializable",
  "data": "!",
  "entrypoint": "./src/main.ts",
  "release": "1.2.3"
}
```

#### 2. Integration

We add a `ModuleMetadata` integration to `@sentry/integrations` with the sole purpose of dumping the injected data onto stackframes. I propose the injected objects are dumped onto the stack frames 1:1 inside a `module_data` property.

We need to make sure we remove the `module_data` properties before sending to Sentry in order not to confuse Relay and to save bandwidth.

#### Next steps

The plugins and the integrations are enough proof-of concept for now. Right now users will still have to write a bit of boilerplate to filter out the right events or to multiplex but we will solve this as a next step as options/callbacks inside the `ModuleMetadata` plugin.

**Comment by AbhiPrasad** [comment]
> We add a ModuleMetadata integration to @sentry/integrations

I'd rather just put this into core/browser - I don't think this needs to be used in node or other runtimes? Just browser JavaScript right?

> We need to make sure we remove the module_data properties before sending to Sentry in order not to confuse Relay and to save bandwidth.

We'll also have to make sure that react native/electron/capacitor also removing this our removal logic ends up being in the client processing chain. We ran into this with sdk processing metadata.

**Comment by realkosty** [comment]
> Next steps
> The plugins and the integrations are enough proof-of concept for now. Right now users will still have to write a bit of boilerplate to filter out the right events or to multiplex but we will solve this as a next step as options/callbacks inside the ModuleMetadata plugin.

Nice. Eventually having a very easy to use solution will make for a great public announcement. I'm stoked. This will be a huge competitive differentiator for us.

If any boilerplate is needed in the meantime, let's please make sure to add a complete working example to the docs 🙏

**Comment by csvan** [comment]
Hey team, thanks a TON for working on this. I was just wondering i this has now been released as part of the Webpack plugin? The documentation does not seem to reflect it:

https://www.npmjs.com/package/@sentry/webpack-plugin#_experimentsinjectbuildinformation

**Comment by timfish** [comment]
Ah sorry, it wasn't added to the readme, although I did add docs here:
https://docs.sentry.io/platforms/javascript/guides/cordova/configuration/micro-frontend-support/

**Comment by csvan** [comment]
@timfish missed that, thanks for the pointer!
