### ISSUE TITLE
Inline base64 source maps are ignored and stack trace stays minified

### ISSUE THREAD

**Issue by alexm92** [getsentry/sentry-javascript-bundler-plugins#364]
### Problem Statement

I'm using Webpack + sentry plugin in a project to bundle multiple files into a single `bundle.js`. The issue that I'm facing is that some of the node_modules that I'm using have the source map inline, as base64 json (see module 3).

The Sentry webpack plugin is creating the `debugId` and uploading some source maps, but it seems that it ignores the base64 json and thus the stack trace remains minified

```js
/* 1 */
(function(module, __webpack_exports__, __webpack_require__) {
  // ...
}),

/* 2 */
(function(module, __webpack_exports__, __webpack_require__) {
  // ...
  //# sourceMappingURL=browser.js.map
}),

/* 3 */
(function(module, __webpack_exports__, __webpack_require__) {
  // ...
  //# sourceMappingURL=data:application/json;charset=utf-8;base64,...
}),

// ...
//# sourceMappingURL=bundle.js.map
```

<img width="1094" alt="image" src="https://github.com/getsentry/sentry/assets/2988929/36301e13-673b-4bd1-a5aa-e57180f3d429">

### Solution Brainstorm

Use the decoded `sourceMappingURL` JSON and generate the `debugId` + upload

### Product Area

Issues - Source Maps

**Comment by lforst** [comment]
Hi, so in general Sentry (and the webpack plugin) should support base64 inline sourcemaps.

I believe the problem is with the code you shared. By definition ([and source maps spec](https://sourcemaps.info/spec.html#c13:~:text=The%20generated%20code%20may%20include%20a%20line%20at%20the%20end%20of%20the%20source%2C)), there needs to be only one `sourceMappingURL` comment, and it needs to be at the end of the source file. You cannot put it into random function scopes.

**Comment by alexm92** [comment]
Thanks @lforst, it makes sense. Let me check my webpack config and get back to you, might have something wrong in there.

**Comment by alexm92** [comment]
I checked and you are right @lforst, there should be a single `sourceMappingURL` in the bundle. I had `optimization.minimize = false` in my Webpack config and thus the multiple `sourceMappingURL` (from other modules) in the bundle.

Changing `optimization.minimize = true` solved the issue. Thanks a lot 🙏
