### ISSUE TITLE
Upload sourcemaps for multiple environments

### ISSUE THREAD

**Issue by taobojlen** [getsentry/sentry-javascript-bundler-plugins#532]
We're using `@sentry/vite-plugin` to create releases & upload sourcemaps to Sentry. We have a lot of environments, so this is what our flow looks like:

- Build our Docker image, which runs `vite build` *without* the Sentry plugin
- Deploy this new image to each of our environments
- After each environment has been deployed, run `vite build` again in a post-deploy step, this time with the Sentry plugin configured so it creates the Sentry release w. sourcemaps for that environment.

This is quite inefficient, since we have to build our frontend N+1 times for N environments. Ideally, there would be a way to upload sourcemaps for many environments at once when we build.

Alternatively, if we're using the plugin incorrectly, I'd love to hear it! But I imagine that this is not an uncommon setup.

**Comment by lforst** [comment]
It is strongly recommended to run the plugin exactly when the prod build is running to avoid source maps to be drifting apart between builds.

I still don't understand your setup. Do you deploy the same app multiple times? And do you point each deployment to a separate project in Sentry? If so, we don't support sharing artifacts between projects yet, meaning you have to upload them multiple timess.

**Comment by taobojlen** [comment]
@lforst yes, we deploy our app many times -- we have an environment for each of our customers. they all live in the same sentry project, but as different environments.

so the deployed code will be the same across environments. we want a way to tell sentry "hey, environments A and B were just updated to run version X of our app, so that's the sourcemap to use".

maybe this isn't actually necessary? if we upload the sourcemap once, and create releases via the sentry CLI or github integration, will that work?

**Comment by lforst** [comment]
Currently, you need to upload sourcemaps to each project separately.

**Comment by bastien-pruvost** [comment]
I have the same problem, I have a Vite application with two environments (staging and production). And the code base is not the same (I have new features on staging that I don't have in production yet). I use sentry vite plugin in the deployment CIs to upload the sourcemaps.
But how can I upload different sourcemaps in the same Sentry project but in two different Sentry environments (staging and production) ?

**Comment by lforst** [comment]
@bastien-pruvost I don't think your problem is the same. You are not uploading to two different projects. If you use the default configuration of the vite plugin, everything should just work for you.

**Comment by taobojlen** [comment]
@lforst I don't upload to different Sentry projects either! I just have one project, with multiple environments.

**Comment by lforst** [comment]
The hierarchy goes:
- Project -> Sourcemap (if you use debug IDs which is the default)
- Project -> Release -> Sourcemap (if you use the legacy upload process)

So if you have multiple environments that all send to the same project in Sentry, everything should just work fine.

**Comment by dsteinel** [comment]
I am facing the same problem with a similar setup. My issue is that I have 2 self-hosted Sentry instances (one for development and one for production) but I only run the build once, so the upload only happens to one instance. because of our deployment strategy I can not do another build. So I need to find a way to upload the source maps in the build step twice to 2 different Sentry urls.
My guess is that I need to use a custom script to upload the source maps or am I missing something?

**Comment by lforst** [comment]
@dsteinel I think you could add the plugin twice. I have never tried that out though. Two self-hosted instances is definitely not a pattern we optimize for.

**Comment by dsteinel** [comment]
Ah yes that actually works! Thanks a lot @lforst

**Comment by SteamWind** [comment]
I have the same environment as @bastien-pruvost and I think, it lacks a bit of documentation to handle this kind of different scenarios. Maybe I missed it?

**Comment by lforst** [comment]
@SteamWind in what way? Did you try out a basic setup?

**Comment by EDjur** [comment]
Hey @lforst - we have a similar setup. Multiple deployments split over separate environments in Sentry. We also have UAT/Prod deployments. These often run the same code and therefore, we would like to be able to upload to 2 Sentry projects at the same time. I.e. instead of specifying the project as a string, an array would work better.

We tried adding the plugin twice, but then the debugId hashing gets messed up as the second plugin will get the result of the first plugin as its input, thereby generating a new debugId hash.

There might be other ways around it like disabling `release.inject` for the second plugin, but that's starting to feel a bit hacky. Would be nicer with official support for an array of projects to upload to.
