### ISSUE TITLE
can not disable soucemap 

### ISSUE THREAD

**Issue by ivank-s** [getsentry/sentry-javascript-bundler-plugins#560]
Environment
Next.js version: 12.3.4
Steps to Reproduce
1. Configured Sentry along with sourcemap uploading in a Next.js project.
2. Following the Micro Frontends documentation, added the @sentry/webpack-plugin to next.config.js under webpack plugins.
3. Executed the build process.
Expected Result
Sourcemaps should be uploaded only once.
Actual Result
Sourcemaps are being uploaded twice. The withSentryConfig function uploads the sourcemaps once, and the @sentry/webpack-plugin uploads them a second time. I am unable to find a way to disable the sourcemap upload by @sentry/webpack-plugin.
Additional Information
I am looking for a solution to prevent the @sentry/webpack-plugin from uploading the sourcemaps without affecting the other functionalities provided by the plugin. Any guidance on how to configure or modify the plugin settings to achieve this would be greatly appreciated.

**Comment by s1gr1d** [comment]
Hello thanks for writing. Could you please share a reproduction example? This can be a GitHub repository, Stackblitz, Codesandbox or similar.

**Comment by lforst** [comment]
> Could you please share a reproduction example?

No need for that! I can see the issue here. You should just be able to leave out one or more of the `org`, `project`, `authToken` in the plugin you manually added, and the sourcemaps shouldn't be uploaded.

It's possible that you provided these values through environment variables where you would be kinda stuck. I think we should add an option to opt out of uploading source maps (`sourcemaps.disable`).

In the future, if the plugins grow even more in functionality, we may want to make uploading sourcemaps opt-in because people might want to have isolated features.

**Comment by ivank-s** [comment]
Yes, I agree that we need an option specifically to disable sourcemap uploads. It's important that this feature is distinct from the `org`, `project`, and `authToken` configurations because the `@sentry/next` plugin requires these settings to function correctly for other features, including sourcemap uploads. Having a separate option to disable sourcemap uploads would provide greater flexibility and control without compromising the necessary configurations for Sentry's core functionalities.
