### ISSUE TITLE
How to prevent @sentry/vite-plugin from injecting Sentry to every file?

### ISSUE THREAD

**Issue by lilouartz** [getsentry/sentry-javascript-bundler-plugins#591]
Looks like Sentry injects this to every file:

```ts
(function() {
    try {
        var r = typeof window < "u" ? window : typeof global < "u" ? global : typeof self < "u" ? self : {}
          , t = new Error().stack;
        t && (r._sentryDebugIds = r._sentryDebugIds || {},
        r._sentryDebugIds[t] = "6af1d399-83b0-4d2d-8d81-2b50af19ad83",
        r._sentryDebugIdIdentifier = "sentry-dbid-6af1d399-83b0-4d2d-8d81-2b50af19ad83")
    } catch {}
}
)();
```

How do I disable this?

**Comment by Lms24** [comment]
Hey @lilouartz would you mind letting us know why you want to disable debug id injection? This snippet is injected so that we can better associate the minified stack frames with the correct source maps to show you the unminified stack frames in the Sentry UI. 

> How do I disable this?

You can give our [legacy source maps uploading](https://docs.sentry.io/platforms/javascript/sourcemaps/troubleshooting_js/legacy-uploading-methods/) strategy a try. This won't inject debug id snippets into your code but you'll need to more carefully set up source maps upload

**Comment by lilouartz** [comment]
Feels lame that I have to use something named "legacy" for what seems like a basic ask.

**Comment by Lms24** [comment]
I gave you an alternative. Without having more context as to why you want to achieve this, we cannot prioritize work on this. 

> Hey @lilouartz would you mind letting us know why you want to disable debug id injection?

**Comment by chadgauth** [comment]
I am having the same issue, the issue is Sentry config on vite is injecting an import to my web worker. We should have an ignore list or a way to prevent Sentry from importing on specified files.

**Comment by Lms24** [comment]
@chadgauth you can use the [`sourcemaps.ignore` option](https://www.npmjs.com/package/@sentry/vite-plugin#sourcemapsignore) to disable injecting the debugId snippet into specific files. Vice verca, you can also specify `assets` to limit the injection of debugIds and source map upload to specific file paths (glob patterns work for both).

**Comment by nicolabello** [comment]
This is quite an issue with Angular PWA, as the injected code makes the Service Worker complain about the scripts hash and does not update the PWA as expected
