### ISSUE TITLE
where is ^1.0 version

### ISSUE THREAD

**Issue by Trinyoung** [getsentry/sentry-javascript-bundler-plugins#601]
I was originally using version 1.10.1, but with the update to the taobao mirror address, I wanted to update the local @sentry/webpack-plugin. I switched to the new taobao mirror address, but I can't find the resource. How can I resolve this issue

**Comment by Lms24** [comment]
Hi @Trinyoung thanks for writing in! We don't publish to taobao or any other NPM mirror registry/repository. The only package registry we publish to is NPM. Other places like unpkg or taobao (TIL) probably scrape NPM to get the pacakges. So my best guess is that something went wrong on their end.

On NPM you'll for sure find all 1.x versions of the webpack plugin. For example, the [latest 1.x one](https://www.npmjs.com/package/@sentry/webpack-plugin/v/1.21.0).

I'm going to close this issue because at this time we're not supporting other registries.
